# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "cesium-release-ubuntu"
  config.vm.box = "duniter/cesium_trusty64"
  config.vm.box_url = "https://s3.eu-central-1.amazonaws.com/duniter/vagrant/duniter_trusty64.box"

  config.vm.provision :shell, path: "bootstrap.sh"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
end
