#!/bin/bash

CESIUM_ROOT=/opt/cesium
CESIUM_G1_TEST=/opt/cesium-g1-test
CESIUM_NW=$CESIUM_ROOT/nw

if [[ -f $CESIUM_ROOT/nw.nwb ]]; then
  unzip -q -d $CESIUM_NW $CESIUM_ROOT/nw.nwb
  chmod +x $CESIUM_NW/nw $CESIUM_NW/lib $CESIUM_NW/locales
  ln -s $CESIUM_NW/nw /usr/bin/cesium
fi

chmod +r -R $CESIUM_ROOT

# Create a Cesium for G1-Test
cd /opt
cp -r "$CESIUM_ROOT" "$CESIUM_G1_TEST"
cd "$CESIUM_G1_TEST/nw/"
sed -i 's/"cesium"/"cesium-g1-test"/g' package.json
ln -s "$CESIUM_G1_TEST/nw/nw" /usr/bin/cesium-g1-test

# Change title of Cesium test
sed -i 's/Cesium/Cesium Ğ1-Test/g' cesium/index.html
sed -i 's/g1.duniter/g1-test.duniter/g' cesium/config.js
sed -i 's/g1.data/g1-test.data/g' cesium/config.js
sed -i 's/"g1"/"g1-test"/g' cesium/node.js
sed -i 's/.config\/cesium\//.config\/cesium-g1-test\//g' cesium/node.js

# Change title of Cesium classic
cd "$CESIUM_ROOT/nw/"
sed -i 's/Cesium/Cesium Ğ1/g' cesium/index.html
