#!/bin/bash

CESIUM_ROOT=/opt/cesium
CESIUM_TEST=/opt/cesium-test

chmod +r -R $CESIUM_ROOT

if [[ -f "$CESIUM_ROOT/nw.nwb" ]]; then
  echo "Unpack nw.nwb ..."
  unzip -q -d "$CESIUM_ROOT/nw" "$CESIUM_ROOT/nw.nwb"
  chmod +x $CESIUM_ROOT/nw/nw $CESIUM_ROOT/nw/lib $CESIUM_ROOT/nw/locales
  ln -s $CESIUM_ROOT/nw/nw /usr/bin/cesium
fi

# Create a Cesium for G1-Test
cd /opt
cp -r "$CESIUM_ROOT" "$CESIUM_TEST"
cd "$CESIUM_TEST/nw/"
sed -i 's/"cesium"/"cesium-test"/g' package.json
ln -s "$CESIUM_TEST/nw/nw" /usr/bin/cesium-test

# Change title of Cesium test
sed -i 's/Cesium/Cesium Ğ1-Test/g' splash.html
sed -i 's/Cesium/Cesium Ğ1-Test/g' cesium/index.html
sed -i 's/config\.js/config-test.js/g' cesium/index.html
sed -i 's/"cesium"/"cesium-test"/g' cesium-desktop.js
sed -i 's/"Cesium"/"Cesium Ğ1-Test"/g' cesium-desktop.js

# Change title of Cesium classic
cd "$CESIUM_ROOT/nw/"
sed -i 's/Cesium/Cesium Ğ1/g' splash.html
sed -i 's/Cesium/Cesium Ğ1/g' cesium/index.html
sed -i 's/"Cesium"/"Cesium Ğ1"/g' cesium-desktop.js
