#!/bin/bash

[[ -f /usr/bin/cesium ]] && rm /usr/bin/cesium
[[ -f /usr/bin/cesium-test ]] && rm /usr/bin/cesium-test
[[ -d /opt/cesium ]] && rm -Rf /opt/cesium
[[ -d /opt/cesium-test ]] && rm -Rf /opt/cesium-test
