#!/bin/bash

[[ -f /usr/bin/cesium ]] && rm /usr/bin/cesium
[[ -f /usr/bin/cesium-g1-test ]] && rm /usr/bin/cesium-g1-test
[[ -f /usr/bin/cesium-desktop ]] && rm -f /usr/bin/cesium-desktop
[[ -d /opt/cesium ]] && rm -Rf /opt/cesium
[[ -d /opt/cesium-g1-test ]] && rm -Rf /opt/cesium-g1-test
