# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "cesium-release-windows"

  config.vm.box = "duniter/cesium_win7"
  #config.vm.box_url = "https://s3.eu-central-1.amazonaws.com/duniter/vagrant/duniter_win7.box"
  config.vm.box_url = "./duniter_win7.box"

  config.vm.provision :shell, path: "build.bat", run: 'always'

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end
end
