# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "duniter-release-windows-server"
  config.vm.box = "gusztavvargadr/windows-server"
  config.vm.box_version = "2102.0.2312"
  config.vm.box_url = "windows-server-2022.box"

  # Old windows 7 VM
  #config.vm.define "duniter-release-windows"
  #config.vm.box = "https://s3.eu-central-1.amazonaws.com/duniter/vagrant/duniter_win7.box"
  #config.vm.box_url = "duniter_win7.box"
  #config.vm.boot_timeout = 900
  #config.vm.network "forwarded_port", guest: 3389, host: 3390

  config.vm.provision :shell, path: "build.bat", run: 'always'

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end
end
